# Generated by Django 3.1.4 on 2021-01-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('level_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('1', 'Main Company'), ('2', 'Company'), ('3', 'Purchase Organisation'), ('4', 'Purchase Group'), ('5', 'Location'), ('6', 'Plants'), ('7', 'Storage Locations'), ('8', 'Cost Cermters'), ('9', 'Departments')], default='2', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LevelPermisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('perm_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('1', 'Main Company'), ('2', 'Company'), ('3', 'Purchase Organisation'), ('4', 'Purchase Group'), ('5', 'Location'), ('6', 'Plants'), ('7', 'Storage Locations'), ('8', 'Cost Cermters'), ('9', 'Departments')], default='2', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usermapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('level_map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permissionmapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('level_map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.level')),
                ('perm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.levelpermisions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LevelMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor', to='app1.level')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='app1.level')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
